//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP_Chernishov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int RequestId { get; set; }
        public System.DateTime RequestData { get; set; }
        public Nullable<int> RequestPatient { get; set; }
        public Nullable<int> RequestSpecialist { get; set; }
        public string RequestDescription { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
